name: Symbaa
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  http: ^1.2.2
  fluttertoast: ^8.2.6
  provider: ^6.1.2
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  figma_squircle: ^0.5.3
  pinput: ^5.0.0
  package_info_plus: ^8.0.0
  expansion_tile_group: ^1.2.6
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.1
  country_picker: ^2.0.26
  onesignal_flutter: ^5.2.4
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/anim/
    - lib/lang/en.json

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf

    - family: ExtraBold
      fonts:
        - asset: assets/fonts/Manrope-ExtraBold.ttf

    - family: ExtraLight
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/Manrope-Light.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Manrope-Medium.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf

    - family: SemiBold
      fonts:
        - asset: assets/fonts/Manrope-SemiBold.ttf





